language: node_js
node_js:
- '8'

script:
- npm run build

before_deploy:
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  on:
    tags: true
    repo: IgniteUI/igniteui-sassdoc-theme
    branch: master
  api_key:
    secure: nhjbD22cfoNeViOspWDY76kDkzQST4LPFLUwVigIdZ3bmiuQ5/N4ZRslZgWelHlrxeKrway7QwL1WK8zAWXM5MZ5lll/K6F1Y3dqUJ6Hw9e+Z9Cw+earLDGZQF3F2mV3yqQYfV7z/pD3a4rClEDIwYxwUIutxGqFFb7p2hKXZEmzt1gm7bRhd6UoaxDL1MtMRn4O2+5NXQrSrVA8N1yIywLwy84Zupje0SNO2fxzKP65WXe8Y65rQ65x5xZEmkmM44nfkMutpHHZeDs6ZB25YW1bZzpBWGaLe9PR/6DbP7gPTD0Vlu/lEMjwj30AgysFJYiATbi3Hk1CihS03Ha4ebUP2NFuGS9ToCMw3+YzEWFy3FlspZqeJ8+B83oxReuk1M9FnsluRL4RpzDGOxbD+AAlrPijviCyvldjS79QZcSBy/sHnICST7Q2UmlGksgv2lnxMxObKwTaxw+CoCC/+0PyIc+H0qkTmQUZprmFf/vjv3RATvKDyJs0GuOOhDsFFI7eYUNlBq/y4GHXU5rEX/kp2XuY7tOLg2LPaSjaUmR2DOy9qZ7fPDMPUh3dVLfJYIWmDjpvaNgszEJwLAhzGa1Yyo0j6OFX9IHuJiMCxLj1Sb00eisG32nAOfo1KwNgtv1aib6JriG4IsMOjme37RwNnDcoMFPYVbGsXow8o7s=
