# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: echo ${VERSION}

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Define NPM tag
        run: if [[ ${VERSION} == *"alpha"* || ${VERSION} == *"beta"* || ${VERSION} == *"rc"* ]]; then echo "NPM_TAG=next"; else echo "NPM_TAG=latest"; fi >> $GITHUB_ENV
      - run: echo ${NPM_TAG}

      - name: Create package version
        run: npm version ${VERSION} --no-git-tag-version --save --allow-same-version --verbose
        working-directory: ./

      - name: Publish igniteui-sassdoc-theme
        run: npm publish --tag ${NPM_TAG}
        working-directory: ./
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
